name: label
on:
  pull_request:
    types: [review_requested]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.PAT }}
          dot: true
